name: deploy_frontend
# Deploys when push is made to frontend directory
# Test

on:
    push:
        branches: [ main ]
        paths:
        - 'frontend/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:            
    - uses: actions/checkout@v2
    - uses: azure/login@v1
      with:
          creds: ${{ secrets.AZURE_RESUME_SECRET }}

    - name: Upload to blob storage
      uses: azure/CLI@v1
      with:
        azcliversion: 2.0.72
        inlineScript: |
<<<<<<< HEAD
            az storage blob upload-batch --account-name resumestorage1175 -d '$web' -s frontend/
=======
            az storage blob upload-batch --account-name <STORAGE_ACCOUNT_NAME> -d '$web' -s frontend/
>>>>>>> b696dc26d26e7326906a53f48e30eb32135fae16
    - name: Purge CDN endpoint
      uses: azure/CLI@v1
      with:
        azcliversion: 2.0.72
        inlineScript: |
           az cdn endpoint purge --content-paths  "/*" --profile-name "myresumecdn" --name "myresumecdn" --resource-group "azureresume-rg"

  # Azure logout 
    - name: logout
      run: |
            az logout
